function(SetupConfig)
	if(WIN32)
		add_compile_definitions(FLAX_WINDOWS)
	elseif(UNIX)
		add_compile_definitions(FLAX_LINUX)
	endif()

	if(WIN32)
		add_compile_definitions(FORCEINLINE=__forceinline)
		add_compile_definitions(NOINLINE=__declspec\(noinline\))
		add_compile_definitions(INLINE=__inline)
		add_compile_definitions(NULLPTR=decltype\(nullptr\)\(\))
		add_compile_definitions(RESTRICT=__restrict)
		add_compile_definitions(NODISCARD=\[\[nodiscard\]\])
	elseif(UNIX)
		add_compile_definitions(FORCEINLINE=__attribute__\(\(always_inline\)\))
		add_compile_definitions(NOINLINE=__attribute__\(\(noinline\)\))
		add_compile_definitions(INLINE=inline)
		add_compile_definitions(NULLPTR=nullptr)
		add_compile_definitions(RESTRICT=__restrict__)
		add_compile_definitions(NODISCARD=\[\[nodiscard\]\])
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Debug")
		add_compile_definitions(FLAX_DEBUG)
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Release")
		add_compile_definitions(FLAX_RELEASE)
	endif()
endfunction()